[2024-10-23T20:53:33.807+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-23T20:53:33.822+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DataPipeline.process_data manual__2024-10-23T20:53:28.397435+00:00 [queued]>
[2024-10-23T20:53:33.829+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DataPipeline.process_data manual__2024-10-23T20:53:28.397435+00:00 [queued]>
[2024-10-23T20:53:33.829+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-10-23T20:53:33.838+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): process_data> on 2024-10-23 20:53:28.397435+00:00
[2024-10-23T20:53:33.844+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=4311) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-23T20:53:33.846+0000] {standard_task_runner.py:63} INFO - Started process 4313 to run task
[2024-10-23T20:53:33.846+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'DataPipeline', 'process_data', 'manual__2024-10-23T20:53:28.397435+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/src/***.py', '--cfg-path', '/tmp/tmpamg7hmiz']
[2024-10-23T20:53:33.848+0000] {standard_task_runner.py:91} INFO - Job 102: Subtask process_data
[2024-10-23T20:53:33.880+0000] {task_command.py:426} INFO - Running <TaskInstance: DataPipeline.process_data manual__2024-10-23T20:53:28.397435+00:00 [running]> on host 6c58daef65ee
[2024-10-23T20:53:33.950+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='MLopsProjectGroup6' AIRFLOW_CTX_DAG_ID='DataPipeline' AIRFLOW_CTX_TASK_ID='process_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-23T20:53:28.397435+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-23T20:53:28.397435+00:00'
[2024-10-23T20:53:33.951+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-23T20:53:33.967+0000] {HandlingNullValues.py:27} INFO - Loading CSV data for processing
[2024-10-23T20:53:34.044+0000] {HandlingNullValues.py:33} INFO - DataFrame shape: (41188, 1)
[2024-10-23T20:53:34.056+0000] {HandlingNullValues.py:41} INFO - DataFrame info saved to /opt/***/dags/../data/processed/dataframe_info.csv
[2024-10-23T20:53:34.076+0000] {HandlingNullValues.py:46} INFO - DataFrame description saved to /opt/***/dags/../data/processed/dataframe_description.csv
[2024-10-23T20:53:34.078+0000] {HandlingNullValues.py:51} INFO - Found 12 duplicate rows. Dropping duplicates.
[2024-10-23T20:53:34.083+0000] {HandlingNullValues.py:53} INFO - Duplicate rows dropped.
[2024-10-23T20:53:34.087+0000] {HandlingNullValues.py:68} INFO - No features dropped
[2024-10-23T20:53:34.288+0000] {HandlingNullValues.py:72} INFO - Processed data saved as CSV at /opt/***/dags/../data/processed/processed_data.csv
[2024-10-23T20:53:34.290+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-23T20:53:34.290+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-23T20:53:34.299+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=DataPipeline, task_id=process_data, run_id=manual__2024-10-23T20:53:28.397435+00:00, execution_date=20241023T205328, start_date=20241023T205333, end_date=20241023T205334
[2024-10-23T20:53:34.341+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-23T20:53:34.356+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-23T20:53:34.358+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
