[2024-10-26T07:02:11.758+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-26T07:02:11.767+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DataPipeline.datatype_format manual__2024-10-26T07:02:07.670698+00:00 [queued]>
[2024-10-26T07:02:11.772+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DataPipeline.datatype_format manual__2024-10-26T07:02:07.670698+00:00 [queued]>
[2024-10-26T07:02:11.773+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-10-26T07:02:11.778+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): datatype_format> on 2024-10-26 07:02:07.670698+00:00
[2024-10-26T07:02:11.781+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=280) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-26T07:02:11.786+0000] {standard_task_runner.py:63} INFO - Started process 282 to run task
[2024-10-26T07:02:11.783+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'DataPipeline', 'datatype_format', 'manual__2024-10-26T07:02:07.670698+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/src/***.py', '--cfg-path', '/tmp/tmph9iw4t5r']
[2024-10-26T07:02:11.786+0000] {standard_task_runner.py:91} INFO - Job 65: Subtask datatype_format
[2024-10-26T07:02:11.804+0000] {task_command.py:426} INFO - Running <TaskInstance: DataPipeline.datatype_format manual__2024-10-26T07:02:07.670698+00:00 [running]> on host 7e8a88eeae3d
[2024-10-26T07:02:11.839+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='MLopsProjectGroup6' AIRFLOW_CTX_DAG_ID='DataPipeline' AIRFLOW_CTX_TASK_ID='datatype_format' AIRFLOW_CTX_EXECUTION_DATE='2024-10-26T07:02:07.670698+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-26T07:02:07.670698+00:00'
[2024-10-26T07:02:11.840+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-26T07:02:11.845+0000] {HandlingNullValues.py:35} INFO - Starting data processing
[2024-10-26T07:02:11.845+0000] {HandlingNullValues.py:36} INFO - Starting data processing
[2024-10-26T07:02:11.845+0000] {HandlingNullValues.py:35} INFO - Input file: None
[2024-10-26T07:02:11.845+0000] {HandlingNullValues.py:36} INFO - Input file: None
[2024-10-26T07:02:11.846+0000] {HandlingNullValues.py:38} ERROR - Input file not found: None
[2024-10-26T07:02:11.846+0000] {HandlingNullValues.py:39} ERROR - Input file not found: None
[2024-10-26T07:02:11.846+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-26T07:02:11.846+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-26T07:02:11.849+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=DataPipeline, task_id=datatype_format, run_id=manual__2024-10-26T07:02:07.670698+00:00, execution_date=20241026T070207, start_date=20241026T070211, end_date=20241026T070211
[2024-10-26T07:02:11.886+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-26T07:02:11.893+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-26T07:02:11.894+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
