[2024-10-26T06:38:08.743+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-26T06:38:08.755+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DataPipeline.load_data manual__2024-10-26T06:38:06.584004+00:00 [queued]>
[2024-10-26T06:38:08.759+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DataPipeline.load_data manual__2024-10-26T06:38:06.584004+00:00 [queued]>
[2024-10-26T06:38:08.759+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-10-26T06:38:08.765+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data> on 2024-10-26 06:38:06.584004+00:00
[2024-10-26T06:38:08.768+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=66) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-26T06:38:08.769+0000] {standard_task_runner.py:63} INFO - Started process 68 to run task
[2024-10-26T06:38:08.770+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'DataPipeline', 'load_data', 'manual__2024-10-26T06:38:06.584004+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/src/***.py', '--cfg-path', '/tmp/tmpnzb16zvu']
[2024-10-26T06:38:08.771+0000] {standard_task_runner.py:91} INFO - Job 49: Subtask load_data
[2024-10-26T06:38:08.791+0000] {task_command.py:426} INFO - Running <TaskInstance: DataPipeline.load_data manual__2024-10-26T06:38:06.584004+00:00 [running]> on host 7e8a88eeae3d
[2024-10-26T06:38:08.829+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='MLopsProjectGroup6' AIRFLOW_CTX_DAG_ID='DataPipeline' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-26T06:38:06.584004+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-26T06:38:06.584004+00:00'
[2024-10-26T06:38:08.829+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-26T06:38:08.835+0000] {LoadData.py:34} INFO - Starting data loading process
[2024-10-26T06:38:08.835+0000] {LoadData.py:35} INFO - Starting data loading process
[2024-10-26T06:38:08.835+0000] {LoadData.py:34} INFO - Using pickle file: None
[2024-10-26T06:38:08.835+0000] {LoadData.py:35} INFO - Using pickle file: None
[2024-10-26T06:38:08.835+0000] {LoadData.py:37} ERROR - Pickle file not found: None
[2024-10-26T06:38:08.836+0000] {LoadData.py:38} ERROR - Pickle file not found: None
[2024-10-26T06:38:08.836+0000] {python.py:237} INFO - Done. Returned value was: False
[2024-10-26T06:38:08.836+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-26T06:38:08.843+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=DataPipeline, task_id=load_data, run_id=manual__2024-10-26T06:38:06.584004+00:00, execution_date=20241026T063806, start_date=20241026T063808, end_date=20241026T063808
[2024-10-26T06:38:08.868+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-26T06:38:08.880+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-26T06:38:08.881+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
