[2024-10-26T06:23:19.625+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-26T06:23:19.637+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DataPipeline.datatype_format manual__2024-10-26T06:23:15.343521+00:00 [queued]>
[2024-10-26T06:23:19.640+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DataPipeline.datatype_format manual__2024-10-26T06:23:15.343521+00:00 [queued]>
[2024-10-26T06:23:19.640+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-10-26T06:23:19.644+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): datatype_format> on 2024-10-26 06:23:15.343521+00:00
[2024-10-26T06:23:19.647+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=145) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-26T06:23:19.648+0000] {standard_task_runner.py:63} INFO - Started process 147 to run task
[2024-10-26T06:23:19.649+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'DataPipeline', 'datatype_format', 'manual__2024-10-26T06:23:15.343521+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/src/***.py', '--cfg-path', '/tmp/tmplnl44eg9']
[2024-10-26T06:23:19.650+0000] {standard_task_runner.py:91} INFO - Job 33: Subtask datatype_format
[2024-10-26T06:23:19.666+0000] {task_command.py:426} INFO - Running <TaskInstance: DataPipeline.datatype_format manual__2024-10-26T06:23:15.343521+00:00 [running]> on host 7e8a88eeae3d
[2024-10-26T06:23:19.699+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='MLopsProjectGroup6' AIRFLOW_CTX_DAG_ID='DataPipeline' AIRFLOW_CTX_TASK_ID='datatype_format' AIRFLOW_CTX_EXECUTION_DATE='2024-10-26T06:23:15.343521+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-26T06:23:15.343521+00:00'
[2024-10-26T06:23:19.699+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-26T06:23:19.704+0000] {HandlingNullValues.py:35} INFO - Starting data processing
[2024-10-26T06:23:19.704+0000] {HandlingNullValues.py:36} INFO - Starting data processing
[2024-10-26T06:23:19.704+0000] {HandlingNullValues.py:35} INFO - Input file: None
[2024-10-26T06:23:19.705+0000] {HandlingNullValues.py:36} INFO - Input file: None
[2024-10-26T06:23:19.705+0000] {HandlingNullValues.py:38} ERROR - Input file not found: None
[2024-10-26T06:23:19.705+0000] {HandlingNullValues.py:39} ERROR - Input file not found: None
[2024-10-26T06:23:19.705+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-26T06:23:19.706+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-26T06:23:19.708+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=DataPipeline, task_id=datatype_format, run_id=manual__2024-10-26T06:23:15.343521+00:00, execution_date=20241026T062315, start_date=20241026T062319, end_date=20241026T062319
[2024-10-26T06:23:19.746+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-26T06:23:19.753+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-26T06:23:19.753+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
