[2024-10-26T07:24:13.958+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-26T07:24:13.967+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DataPipeline.datatype_format manual__2024-10-26T07:24:08.712533+00:00 [queued]>
[2024-10-26T07:24:13.970+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DataPipeline.datatype_format manual__2024-10-26T07:24:08.712533+00:00 [queued]>
[2024-10-26T07:24:13.970+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-10-26T07:24:13.975+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): datatype_format> on 2024-10-26 07:24:08.712533+00:00
[2024-10-26T07:24:13.978+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=666) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-26T07:24:13.979+0000] {standard_task_runner.py:63} INFO - Started process 668 to run task
[2024-10-26T07:24:13.980+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'DataPipeline', 'datatype_format', 'manual__2024-10-26T07:24:08.712533+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/src/***.py', '--cfg-path', '/tmp/tmpxdlnbva_']
[2024-10-26T07:24:13.981+0000] {standard_task_runner.py:91} INFO - Job 97: Subtask datatype_format
[2024-10-26T07:24:13.998+0000] {task_command.py:426} INFO - Running <TaskInstance: DataPipeline.datatype_format manual__2024-10-26T07:24:08.712533+00:00 [running]> on host 7e8a88eeae3d
[2024-10-26T07:24:14.037+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='MLopsProjectGroup6' AIRFLOW_CTX_DAG_ID='DataPipeline' AIRFLOW_CTX_TASK_ID='datatype_format' AIRFLOW_CTX_EXECUTION_DATE='2024-10-26T07:24:08.712533+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-26T07:24:08.712533+00:00'
[2024-10-26T07:24:14.038+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-26T07:24:14.045+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-26T07:24:14.046+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: handle_data_types() missing 1 required positional argument: 'data'
[2024-10-26T07:24:14.052+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=DataPipeline, task_id=datatype_format, run_id=manual__2024-10-26T07:24:08.712533+00:00, execution_date=20241026T072408, start_date=20241026T072413, end_date=20241026T072414
[2024-10-26T07:24:14.057+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 97 for task datatype_format (handle_data_types() missing 1 required positional argument: 'data'; 668)
[2024-10-26T07:24:14.079+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-26T07:24:14.092+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-26T07:24:14.092+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
